# Generated by Django 4.0.4 on 2022-05-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_expression', models.CharField(max_length=500)),
                ('tex_string', models.CharField(max_length=500)),
            ],
        ),
    ]
