# Generated by Django 4.0.4 on 2022-05-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryentry',
            name='variable_name',
            field=models.CharField(default='x', max_length=10),
            preserve_default=False,
        ),
    ]
